version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET}

    volumes:
      # Database & Private Data Path (Default: ./data)
      - ${DB_PATH:-./data}:/app/data
      # Vendor Logos Path (Default: ./public/vendor_logos)
      - ${LOGOS_PATH:-./public/vendor_logos}:/app/public/vendor_logos
    restart: always

